[package]
name = "remarkable-tools-meta"
version = "1.0.0"
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.remarkable-tools]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.41.2"