[package]
name = "smart-send-meta"
version = "1.0.0"
edition = "2021"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.smart-send]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.4"
