[package]
name = "smart-send"
version = "1.0.0"
authors = ["Remarkable Tools"]
edition = "2021"
publish = false

[lib]
path = "src/smart_send.rs"

[dependencies.multiversx-sc]
version = "0.43.4"

[dev-dependencies.multiversx-sc-scenario]
version = "0.43.4"

[dev-dependencies]
num-bigint = "0.4.2"