// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    smart_send
    (
        init => init
        upgrade => upgrade
        smartSend => token_distribution
        smartNftSend => nft_distribution
        smartSftSend => sft_distribution
        addUser => add_user
        removeUser => remove_user
        getAllowedUsers => allowed_users
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
