// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    remarkable_tools
    (
        init => init
        upgrade => upgrade
        generate => generate
        claimOwnership => claim_ownership
        setSourceContract => set_source_contract
        setContractPrice => set_contract_price
        getSourceContract => source_contract
        getGenerationPrice => contract_price
        getUnclaimedContracts => unclaimed_contracts
        smartSend => smart_send
        smartNftSend => smart_nft_send
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
