// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    remarkable_tools
    (
        init => init
        upgrade => upgrade
        generate => generate
        claimOwnership => claim_ownership
        setSourceContract => set_source_contract
        setContractPrice => set_contract_price
        smartSend => token_distribution
        smartNftSend => nft_distribution
        smartSftSend => sft_distribution
        getSourceContract => source_contract
        getGenerationPrice => contract_price
        getUnclaimedContracts => unclaimed_contracts
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
